### ISSUE TITLE
Mod not find

### ISSUE THREAD

**Issue by Wintertjess** [ThinkingStudios/MaLiLib-Forge#32]
![image](https://github.com/ThinkingStudios/MaLiLib-Forge/assets/145144033/5ad95389-6141-4cf5-9cb1-74c1563f9ad7)

**Comment by TexBlock** [comment]
I will fix in 0.1.6

**Comment by Wintertjess** [comment]
Do u know when its done?

**Comment by GeggsLegs** [comment]
I'm using MaFgLib-0.1.8-mc1.19.2.jar
The issue still persists
![image](https://github.com/ThinkingStudios/MaLiLib-Forge/assets/89689465/019dc903-c5b5-413d-8682-e39894f1ee5a)

**Comment by Wintertjess** [comment]
I hope its fixing fast..

**Comment by TexBlock** [comment]
fixed in newer version

**Comment by Koala-ofu** [comment]
![298607112-9234addb-5fb4-4bef-ab5c-8fe217dd70b0](https://github.com/ThinkingStudios/MaLiLib-Forge/assets/137512867/87de7088-4411-4a02-9dd5-257bed147a1a)

Still have problems

**Comment by Wintertjess** [comment]
Yup

**Comment by AsheX1** [comment]
> ![298607112-9234addb-5fb4-4bef-ab5c-8fe217dd70b0](https://private-user-images.githubusercontent.com/137512867/298610824-87de7088-4411-4a02-9dd5-257bed147a1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyMTg5NDYsIm5iZiI6MTcwNjIxODY0NiwicGF0aCI6Ii8xMzc1MTI4NjcvMjk4NjEwODI0LTg3ZGU3MDg4LTQ0MTEtNGEwMi05ZGQ1LTI1N2JlZDE0N2ExYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNVQyMTM3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZWRlYjM5YjBhOGFjMjRjZGVkZGFlZDRjM2RmNWZlMjU1NzU0MWJjMzY0MTFkYWI0MDE4NjkyMzAyYWU4N2UwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cC6Y1eHiE3gijIFW-PIDTCB6MtElRBkrtS57wMTbt7M)
> 
> Still have problems

the 0.1.6 jar is broken for  1.20.1 i fixed it in this post grab it from there #38
